spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/payment-db

mercado:
  pago:
    access:
      token: ${MERCADO_PAGO_ACCESS_TOKEN}

order:
  payment:
    status:
      url: ${ORDER_SERVICE_URL:http://localhost:8080/orders}

server:
  port: 8083
